### ISSUE TITLE
Arsenal Modules Rewrite

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/AresModAchillesExpansion#200]
There are a bunch of concerns with the old Ares Arsenal modules.
Tasks to address:
- [x] Low performance
- [x] Creating Achilles dependencies. #120
- [x] Not adding wanted items #196
- [x] Format limit can be exceeded when copying items. #189
- [x] Add ACE 3.12.0 Arsenal Compatability acemod/ACE3#5734

* Perhaps create a dialog that allows the user to add his own whitelisted items.
