### ISSUE TITLE
Task List Hotfix 1.0.1

### ISSUE THREAD

**Issue by oOKexOo** [ArmaAchilles/AresModAchillesExpansion#230]
#### Arsenal Modules:
- [ ] Create custom does not use ACE3's arsenal.
- [ ] Inventory attribute window does not use ACE3's arsenal.
- [ ] Copy/Paste arsenal is broken when ACE3 is running (presumably because of the two points above).
#### Suppressive fire:
- [x] Does not work properly for certain soldier types (e.g. GL).
- [x] Hangun can be selected despite the fact that they don't work.
#### Create teleporter:
- [ ] Unknown instabilities => revert back to 0.0.9c.
####  Add/remove editable objects module:
- [x] Not all objects can be added/removed.

**Comment by unhappytroll** [comment]
Additional bugs had seen so far:

- Create  Full Arsenal does not work at all, **if ACE was loaded**. Also it breaks ACE Arsenal module.

- ACE Medical menu (Heal/Injury) still available without ACE loaded.
